dist: xenial
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
    update: true
services:
  - docker
git:
  depth: false
language: java
jdk: oraclejdk11
before_script:
  - sqlite3 -version
  - make -version
  - make clean-all
  - make sqlite-db-build
  - curl -fsSL https://get.nextflow.io | bash
  - echo $PATH
  - export PATH=`pwd`:$PATH
  - echo $PATH
  - nextflow -h
script: "./gradlew test"
after_success:
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
