# WES NEXTFLOW - STARTER KIT WES BUNDLED WITH NEXTFLOW

##################################################
# WES BUILDER CONTAINER
##################################################
FROM ga4gh/ga4gh-starter-kit-wesbuilder as wesbuilder

##################################################
# DOCKER CONTAINER
##################################################
FROM docker:20.10.8-dind-alpine3.13 as dockerbuilder

##################################################
# FINAL CONTAINER
##################################################
FROM adoptopenjdk/openjdk12:jre-12.0.2_10-debian

ARG VERSION

# Get docker
COPY --from=dockerbuilder /usr/local/bin/docker /usr/local/bin/docker

# INSTALL NEXTFLOW v21.04.0(this step could also be cached probably)
# TODO: the version of nextflow should be configurable
WORKDIR /home/user
RUN bash
RUN apt-get update
RUN apt-get install -y wget
RUN wget https://github.com/nextflow-io/nextflow/releases/download/v21.04.0/nextflow
RUN chmod -R 777 .
ENV PATH="/home/user:${PATH}"

# When nextflow -v is run the first time, it takes about 15 sec. This step breaks if nextflow is not installed
RUN echo $(nextflow -v)

# Get java app
WORKDIR /home/user/app
COPY --from=wesbuilder /usr/src/app/ga4gh-starter-kit-wes-${VERSION}.jar ga4gh-starter-kit-wes.jar   

# Get database
WORKDIR /home/user/db
COPY --from=wesbuilder /usr/src/db/ga4gh-starter-kit.dev.db ga4gh-starter-kit.dev.db
COPY src/test/resources src/test/resources

ENTRYPOINT [ "java", "-jar", "/home/user/app/ga4gh-starter-kit-wes.jar" ]
