# CROMWELL DOCKER - CROMWELL BUNDLED WITH DOCKER CLI APP

FROM docker:20.10.8-dind-alpine3.13 as dockerbuilder

FROM broadinstitute/cromwell:74

COPY --from=dockerbuilder /usr/local/bin/docker /usr/local/bin/docker
