version: "3.9"
services:
  wes:
    image: ga4gh/ga4gh-starter-kit-wes:test-standalone
    hostname: wes.ga4gh.org
    ports:
      - "4545:4545"
      - "4546:4546"
    volumes:
      - ../../src/test/resources/config:/config
      - "/tmp/shared/cromwell/runs:/tmp/shared/cromwell/runs"
    command: -c /config/wdl-integration-tests-config.yml
  cromwell-docker:
    image: ga4gh/cromwell-docker:test
    hostname: cromwell-docker.ga4gh.org
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/shared/cromwell/runs:/tmp/shared/cromwell/runs"
    working_dir: /tmp/shared/cromwell/runs
    command: server
